name: Setup-Test-Appli

description: 'Setup Test Appli'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  version:
    description: 'The version to use.'
    default: 'v0.0.32'
    required: true
  type:
    description: 'The technology to test.'
    default: 'atps'
    required: true
  user:
    description: 'The database user name(s) (comma-separated list if several databases to create).'
    required: false
  password:
    description: 'The database user password.'
    required: false
  service:
    description: 'The service to use.'
    default: 'create-database'
    required: true

outputs:
  host:
    description: 'The database hostname'
    value: ${{ steps.run.outputs.host }}
  service:
    description: 'The database service'
    value: ${{ steps.run.outputs.service }}
  version:
    description: 'The database version'
    value: ${{ steps.run.outputs.version }}
  connection_string:
    description: 'The database connection string'
    value: ${{ steps.run.outputs.connection_string }}

runs:
  using: 'composite'
  steps:
    - name: 'Install binaries'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: ${GITHUB_ACTION_PATH}/setup-test.sh

    - name: 'Run'
      id: run
      shell: bash
      env:
        RUNID: ${{ github.run_number }}
      run: |
        ${GITHUB_ACTION_PATH}/setup-testpilot --${{ inputs.service }} \
        --user "${{ inputs.user }}" --password "${{ inputs.password }}" --type "${{ inputs.type }}" >> $GITHUB_OUTPUT
# skip-testing --owner hibernate --repository hibernate-orm --sha 2bd500bb009d794b6b7dd5b3472eee6985847a07 --prefix-list documentation/,README.adoc,branching.adoc,dialects.adoc,hibernate_logo.gif,lgpl.txt,migration-guide.adoc,release_notes.md,test-case-guide.adoc