name: Setup-Test-Appli

description: 'Setup Test Appli'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  version:
    description: 'The version to use.'
    default: 'v0.0.19'
    required: true
  type:
    description: 'The technology to test.'
    default: 'atps'
    required: true
  service:
    description: 'The service to use.'
    default: 'create-schema'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install binaries'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: "${GITHUB_ACTION_PATH}/setup-test.sh"
    - name: 'Run'
      shell: bash
      env:
        RUNID: ${{ github.run_number }}
        SERVICE: ${{ github.service }}
      run: "${GITHUB_ACTION_PATH}/setup-testpilot --${SERVICE}"