name: Setup-Test-Appli

description: 'Setup Test Appli'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  version:
    description: 'The version to use.'
    default: 'v1.0.19'
    required: true
  action:
    description: 'The action to run (create*, delete, skip-testing).'
    default: 'create'
    required: true
  oci-service:
    description: 'The Oracle Cloud Infrastructure service to test.'
    default: 'autonomous-transaction-processing-serverless'
    required: true
  user:
    description: 'The database username to be used for database creation. If multiple users (up to 10) are required then enter a comma-separated list of usernames (no space). Limit usernames to 118 chars maximum. Accepted chars are: upper case letters, lower case letters, digits, colon, hyphen, and underscore.'
    required: false
  prefix_list:
    description: 'A comma separated list of file(s) or folder(s) that if changed should not trigger any test (example: folder containing documentation).'
    required: false

outputs:
  database_host:
    description: 'The database hostname.'
    value: ${{ steps.create_or_delete.outputs.database_host }}
  database_service:
    description: 'The database service name.'
    value: ${{ steps.create_or_delete.outputs.database_service }}
  database_password:
    description: 'The database password.'
    value: ${{ steps.create_or_delete.outputs.database_password }}
  database_version:
    description: 'The database version.'
    value: ${{ steps.create_or_delete.outputs.database_version }}
  connection_string_suffix:
    description: 'The database connection string suffix (after @).'
    value: ${{ steps.create_or_delete.outputs.connection_string_suffix }}
  skip_tests:
    description: 'Should skip tests?'
    value: ${{ steps.analyze_commit.outputs.skip_tests }}

runs:
  using: 'composite'
  steps:
    - name: 'Install binaries'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: ${GITHUB_ACTION_PATH}/setup-test.sh

    - name: 'Analyze commit'
      id: analyze_commit
      if: inputs.action == 'skip-testing'
      shell: bash -leo pipefail {0}
      env:
        RUNID: ${{ github.run_number }}
      run: |
        ${GITHUB_ACTION_PATH}/setup-testpilot --skip-testing \
        --owner "${{ github.repository_owner }}" --repository "${{ github.event.repository.name }}" --sha "${{ github.sha }}" \
        --prefix-list "${{ inputs.prefix_list }}"

    - name: 'Create or Delete'
      id: create_or_delete
      if: inputs.action == 'create' || inputs.action == 'delete'
      shell: bash -leo pipefail {0}
      env:
        RUNID: ${{ github.run_number }}
      run: |
        ${GITHUB_ACTION_PATH}/setup-testpilot --${{ inputs.action }} \
        --user "${{ inputs.user }}" --oci-service "${{ inputs.oci-service }}"

