name: Setup-Test-Appli

description: 'Setup Test Appli'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  version:
    description: 'The version to use.'
    default: 'v0.0.25'
    required: true
  type:
    description: 'The technology to test.'
    default: 'atps'
    required: true
  user:
    description: 'The database user name.'
    required: false
  password:
    description: 'The database user password.'
    required: false
  service:
    description: 'The service to use.'
    default: 'create-schema'
    required: true
outputs:
  host:
    description: 'The database hostname'
    value: ${{ steps.run.outputs.host }}
  service:
    description: 'The database service'
    value: ${{ steps.run.outputs.service }}
  version:
    description: 'The database version'
    value: ${{ steps.run.outputs.version }}
  connection_string:
    description: 'The database connection string'
    value: ${{ steps.run.outputs.connection_string }}

runs:
  using: 'composite'
  steps:
    - name: 'Install binaries'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: ${GITHUB_ACTION_PATH}/setup-test.sh
    - name: 'Run'
      id: run
      shell: bash
      env:
        RUNID: ${{ github.run_number }}
        SERVICE: ${{ inputs.service }}
        USER: ${{ inputs.user }}
        PASSWORD: ${{ inputs.password }}
        DB_TYPE: ${{ inputs.type }}
      run: ${GITHUB_ACTION_PATH}/setup-testpilot --${SERVICE} --user ${USER} --password ${PASSWORD} --db-type ${DB_TYPE} >> $GITHUB_OUTPUT
