name: Setup-Test-Appli

description: 'Setup Test Appli'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  version:
    description: 'The Test version to use.'
    default: 'latest'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Download Test'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: "${GITHUB_ACTION_PATH}/setup-test.sh"