= Setup Test
:linkattrs:
:project-owner: llefevre
:project-name:  test
:project-tag:   v1.0.6

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/github/v/release/{project-owner}/{project-name}["GitHub release", link="https://github.com/{project-owner}/{project-name}/releases"]

Sets up link:https://www.oracle.com/database/[Test].

This GitHub Action helps the integration of Test within your GitHub Action workflows. It provides several `actions`:

- `create`: used to request the provisioning of the OCI service to test
- `delete`: used to de-provision the OCI service tested
- `skip-testing`: used to check if this GitHub commit should not perform any non-regression test, for example if changes involve files or folders that do not contain source code. By using the output of this action, numerous GitHub Action workflows can see their runtime durations drastically reduced.

Supported platforms:

- Linux

== Inputs

Following inputs may be used as `step.with` keys:

[%header,cols="<2,<,<,<3",width="100%"]
|===
| Name     | Required | Default         | Description
| action  | Yes      | create | A valid action among: `create`, `delete`, `skip-testing`.
| oci-service |          | autonomous-transaction-processing-serverless            | A valid Oracle Cloud Infrastructure service to be tested.
Valid OCI service are: `autonomous-transaction-processing-serverless`, `base-database-service-19c`, `base-database-service-21c`, and `base-database-service-23ai`.
| user     |          |                 | The database username to be used for database creation. If multiple users are required then enter a comma-separated list of usernames (no space).
| prefix_list |  |  | A comma separated list of file(s) or folder(s) that if changed should not trigger any test (example: folder containing documentation).
|===

== Outputs

Following outputs may be used as `step.if` or for `step.env` keys:

[%header,cols="<2,<,<3",width="100%"]
|===
| Name              | Output of Action | Description
| database_host              | create   | The hostname of the database(s).
| database_service           | create   | The database service name of the database(s).
| database_password          | create   | The database password of the database(s).
| database_version           | create   | The version of the database(s).
| connection_string_suffix | create   | The database connection string suffix (after @), it can be used to build the full JDBC connection string.
| skip_tests        | skip-testing      | 'yes' if tests can be skipped, 'no' otherwise.
|===

== Usage

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    steps:
      # Look if committed files should trigger a build and running tests
      - id: build_guard
        uses: {project-owner}/{project-name}@{project-tag}
        with:
          action: skip-testing
          prefix_list: .github/workflows/ci.yml,README.md,LICENSE,.gitignore

      # Create the database for testing only if tests must be run
      - id: create_database
        uses: {project-owner}/{project-name}@{project-tag}
        if: steps.build_guard.outputs.skip_tests == 'no'
        with:
          oci-service: base-database-service-23ai
          action: create
          user: test
        env:
          TESTPILOT_CLIENT_ID: ${{ secrets.TESTPILOT_CLIENT_ID }}

      # Run the build and the tests against the database
      - name: Run build script
        if: steps.build_guard.outputs.skip_tests == 'no'
        env:
          RUNID: ${{ github.run_number }}
          DATABASE_HOST: ${{ steps.create_database.outputs.database_host }}
          DATABASE_SERVICE: ${{ steps.create_database.outputs.database_service }}
          DATABASE_PASSWORD: ${{ steps.create_database.outputs.database_password }}
        run: ./build.sh
        shell: bash

      # Delete the database for testing only if tests must be run
      - uses: {project-owner}/{project-name}@{project-tag}
        if: steps.build_guard.outputs.skip_tests == 'no'
        with:
          oci-service: base-database-service-23ai
          action: delete
          user: test
        env:
          TESTPILOT_CLIENT_ID: ${{ secrets.TESTPILOT_CLIENT_ID }}

----

