name: GH Actions CI/CD

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: { } # none

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'loiclefevre/test' }}

jobs:
  build:
    permissions:
      contents: write
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check if Git tag exists
        run: echo "HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
#          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B -ntp verify -P native
      - name: Create tar archive
        if: success() && ( ${{ matrix.os }} == 'macos-latest' || ${{ matrix.os }} == 'ubuntu-latest' )
        run: |
          tar -cvf ${{ github.workspace }}/test-${{ matrix.os }}.tar ${{ github.workspace }}/target/test
          gzip ${{ github.workspace }}/test-${{ matrix.os }}.tar
      - name: Create zip archive
        if: success() && ( ${{ matrix.os }} == 'windows-latest' )
        run: Compress-Archive -Path ${{ github.workspace }}/test.exe -Destination ${{ github.workspace }}/test-${{ matrix.os }}.zip
#      - name: Upload native image
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-${{ runner.os }}
#          path: ${{ github.workspace }}/target
      - name: Releasing...
        uses: softprops/action-gh-release@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/test-${{ runner.os }}.tar.gz
          draft: false
          prerelease: false
          make_latest: true
          name: Test v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
#          body_path: CHANGELOG.md
          generate_release_notes: true
