name: GH Actions CI/CD

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: { } # none

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'loiclefevre/test' }}

jobs:
  build:
    permissions:
      contents: write
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check if Git tag exists
        run: echo "HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
#          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B -ntp verify -P native
      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}
          path: ${{ github.workspace }}/target
      - name: Create release
        uses: ncipollo/release-action@v1
        if: success() && github.ref_type == 'tag'
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true
          artifacts: "${{ github.workspace }}/target/test-${{ matrix.os }}"
#          bodyFile: "body.md"
          generateReleaseNotes: true